default_stages: [push, manual]
files: src/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, staging, --branch, main]
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      # - id: requirements-txt-fixer
      - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
      - id: flake8
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
        - id: blacken-docs
          additional_dependencies: [black==21.5b1]
          entry: blacken-docs --skip-errors
  # - repo: https://github.com/PyCQA/pydocstyle
  #   rev: 6.1.1
  #   hooks:
  #      - id: pydocstyle
  #        exclude: ^tests/
  #        stages: [push, manual] #so that intermediate changes can be committed locally
  - repo: https://github.com/psf/black
    rev: 21.6b0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true