name: CI tests
on: 
  workflow_dispatch: ~
  push:
    branches:
      - main
    paths:
      - '**.py'
  pull_request:
    branches:
      - '**'
    paths:
      - '**.py'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.9
    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('src/requirements.txt') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
    - name: Run Linting check
      run: |
        kedro lint
    - name: Run Tests
      run: |
        python -m pytest
